FROM microsoft/dotnet:2.1-sdk-nanoserver-sac2016 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out


# Build runtime image
FROM microsoft/dotnet:2.1-runtime-nanoserver-sac2016
WORKDIR /app
COPY --from=build-env /app/out .

# Expose port 9000
ENV ASPNETCORE_URLS http://+:9000
EXPOSE 9000

ENTRYPOINT ["dotnet", "mywebapi.dll"] 